# Generated by Django 5.0.6 on 2026-05-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFinal',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente_final',
            },
        ),
        migrations.CreateModel(
            name='ContaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adm', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conta_vendedor',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite_lojas', models.IntegerField()),
                ('limite_imagens', models.IntegerField()),
                ('limite_api', models.IntegerField()),
                ('espaco_armazenamento', models.IntegerField()),
            ],
            options={
                'db_table': 'plano',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('configuracoes_marketing', models.JSONField(default=dict)),
                ('subdominio', models.CharField(max_length=100, unique=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contavendedor')),
            ],
            options={
                'db_table': 'loja',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientefinal')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
            ],
            options={
                'db_table': 'carrinho',
                'unique_together': {('loja', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='AGUARDANDO_PAGAMENTO', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clientefinal')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.loja')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('status_transacao', models.CharField(max_length=50)),
                ('id_transacao_gateway', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='api.pedido')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='EventoBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('payload_contexto', models.JSONField(default=dict)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pedido')),
            ],
            options={
                'db_table': 'evento_bi',
            },
        ),
        migrations.AddField(
            model_name='contavendedor',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plano'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_exibicao', models.IntegerField()),
                ('url_arquivo', models.CharField(max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.produto')),
            ],
            options={
                'db_table': 'imagem',
            },
        ),
        migrations.CreateModel(
            name='VariacaoSKU',
            fields=[
                ('id_sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('atributo', models.JSONField(default=dict)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='api.produto')),
            ],
            options={
                'db_table': 'variacao_sku',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_venda_congelado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo_congelado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.pedido')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.variacaosku')),
            ],
            options={
                'db_table': 'item_pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.carrinho')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variacaosku')),
            ],
            options={
                'db_table': 'item_carrinho',
                'unique_together': {('carrinho', 'sku')},
            },
        ),
    ]
