# Generated by Django 5.0.6 on 2026-05-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientefinal')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
            ],
            options={
                'db_table': 'carrinho',
                'unique_together': {('loja', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.carrinho')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variacaosku')),
            ],
            options={
                'db_table': 'item_carrinho',
                'unique_together': {('carrinho', 'sku')},
            },
        ),
    ]
