version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vooap_db
    environment:
      POSTGRES_DB: vooap_db
      POSTGRES_USER: vooap_user
      POSTGRES_PASSWORD: vooap_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54324:5432"

  backend:
    build: ./backend
    container_name: vooap_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://vooap_user:vooap_pass@db:5432/vooap_db
    depends_on:
      - db

volumes:
  postgres_data: